; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
;framework = stm32cube（不用framework了）
;编译配置-D是宏定义，-Idir是include文件目录,读者可按自己项目结构更改
build_flags = 
	-DSTM32F1xx
	-ICore/Inc
	-IDrivers/CMSIS/Include
	-IDrivers/CMSIS/Device/ST/STM32F1xx/Include
	-IDrivers/STM32F1xx_HAL_Driver/Inc
	-IDrivers/STM32F1xx_HAL_Driver/Inc/Legacy
;选择编译文件的所在路径，这里包含了源文件路径，启动文件，驱动库和rtos路径。如果+<*>便是路径下的所以文件，-<.git/>便是忽略.git路径下的文件
build_src_filter = +<Core/Src/> +<./startup_stm32f103xb.s> +<Drivers/STM32F1xx_HAL_Driver/>
;选择链接文件 可能STM32F103XX_FLASH.ld中 "READONLY" 对于部分编译不支持，删掉即可
board_build.ldscript = ./STM32F103xx_FLASH.ld
;选择下载的仿真器，这里是选择的jlink，如果不设置默认stlink
upload_protocol = stlink
extra_scripts = post:scripts/select_stlink_upload.py

;在配置文件分号开头为注释
[platformio]
;将源代码的编译目录移到项目目录下，否则默认src下
src_dir = ./
